{% set name = "huggingface_hub" %}
{% set version = "0.26.5" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/huggingface_hub-{{ version }}.tar.gz
  sha256: 1008bd18f60bfb65e8dbc0a97249beeeaa8c99d3c2fa649354df9fa5a13ed83b

build:
  number: 1
  noarch: python
  entry_points:
    - huggingface-cli=huggingface_hub.commands.huggingface_cli:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - typing_extensions >=3.7.4.3
    - fsspec >=2023.5.0
    - filelock
    - python >={{ python_min }}
    - pyyaml >=5.1
    - packaging >=20.9
    - requests
    - tqdm >=4.42.1
    - typing-extensions >=3.7.4.3

test:
  imports:
    - huggingface_hub
    - huggingface_hub.commands
  commands:
    - pip check
    - huggingface-cli --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/huggingface/huggingface_hub
  summary: Client library to download and publish models on the huggingface.co hub
  license: Apache-2.0
  license_file: LICENSE
  description: |
    The `huggingface_hub` is a client library to interact with the Hugging Face Hub. 
    The Hugging Face Hub is a platform with over 35K models, 4K datasets, and 2K 
    demos in which people can easily collaborate in their ML workflows. The Hub works 
    as a central place where anyone can share, explore, discover, and experiment with 
    open-source Machine Learning.

    With `huggingface_hub`, you can easily download and upload models, extract useful 
    information from the Hub, and do much more. Some example use cases:

    - Downloading and caching files from a Hub repository.
    - Creating repositories and uploading an updated model every few epochs.
    - Extract metadata from all models that match certain criteria (e.g. models for `text-classification`).
    - List all files from a specific repository.

    PyPI: [https://pypi.org/project/huggingface-hub/](https://pypi.org/project/huggingface-hub/)

  doc_url: https://huggingface.co/docs/huggingface_hub
  dev_url: https://github.com/huggingface/huggingface_hub

extra:
  recipe-maintainers:
    - hanouticelina
    - LysandreJik
    - osanseviero
    - Wauplin
    - BastianZim
    - sugatoray
