{% set name = "huggingface_hub" %}
{% set version = "0.2.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/huggingface_hub-{{ version }}.tar.gz
  sha256: ec0680b2d6358bef8ae674c04dcd9411ceb5c61b049e507eab1865383b859de6

build:
  number: 0
  noarch: python
  entry_points:
    - huggingface-cli=huggingface_hub.commands.huggingface_cli:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6.0
  run:
    - filelock
    - python >=3.6.0
    - pyyaml
    - packaging >=20.9
    - requests
    - tqdm
    - typing-extensions >=3.7.4.3
    # Only required for [py<38] but always include so this can be noarch: python
    - importlib_metadata

test:
  imports:
    - huggingface_hub
    - huggingface_hub.commands
  commands:
    - pip check
    - huggingface-cli --help
  requires:
    - pip

about:
  home: https://github.com/huggingface/huggingface_hub
  summary: Client library to download and publish models on the huggingface.co hub
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - BastianZim
