{% set name = "huggingface_hub" %}
{% set version = "0.0.6" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/huggingface/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: df6763dd51e79c084281558e9ab825e673b434f00a95b663e26f511b059af749

build:
  number: 0
  noarch: python
  entry_points:
    - huggingface-cli=huggingface_hub.commands.huggingface_cli:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6.0
  run:
    - filelock
    - python >=3.6.0
    - requests
    - tqdm
    # Only required for [py<38] but always include so this can be noarch: python
    - importlib_metadata

test:
  imports:
    - huggingface_hub
    - huggingface_hub.commands
  commands:
    - pip check
    - huggingface-cli --help
    - pytest tests
  requires:
    - git
    - git-lfs
    - pip
    - pytest
  source_files:
    - tests

about:
  home: https://github.com/huggingface/huggingface_hub
  summary: Client library to download and publish models on the huggingface.co hub
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - BastianZim
