{% set name = "huggingface_hub" %}
{% set version = "0.34.4" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/huggingface_hub-{{ version }}.tar.gz
  sha256: a4228daa6fb001be3f4f4bdaf9a0db00e1739235702848df00885c9b5742c85c

build:
  number: 1
  noarch: python
  entry_points:
    - huggingface-cli=huggingface_hub.commands.huggingface_cli:main
    - hf=huggingface_hub.cli.hf:main
    # Note: This cannot be tested out of the box since it requires `mcp` and `typer` as
    # additional optional dependencies.
    - tiny-agents=huggingface_hub.inference._mcp.cli:app
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - hf-xet >=1.1.3,<2.0.0
    - typing_extensions >=3.7.4.3
    - fsspec >=2023.5.0
    - filelock
    - python >={{ python_min }}
    - pyyaml >=5.1
    - packaging >=20.9
    - requests
    - tqdm >=4.42.1
    - typing-extensions >=3.7.4.3

test:
  imports:
    - huggingface_hub
    - huggingface_hub.commands
  commands:
    - pip check
    - huggingface-cli --help
    - huggingface-cli env
    - hf --help
    - hf env
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/huggingface/huggingface_hub
  summary: Client library to download and publish models on the huggingface.co hub
  license: Apache-2.0
  license_file: LICENSE
  description: |
    The huggingface_hub library allows you to interact with the Hugging Face Hub, a platform democratizing open-source Machine Learning for creators and collaborators. Discover pre-trained models and datasets for your projects or play with the thousands of machine learning apps hosted on the Hub. You can also create and share your own models, datasets and demos with the community. The huggingface_hub library provides a simple way to do all these things with Python.

    PyPI: [https://pypi.org/project/huggingface-hub/](https://pypi.org/project/huggingface-hub/)

  doc_url: https://huggingface.co/docs/huggingface_hub
  dev_url: https://github.com/huggingface/huggingface_hub

extra:
  recipe-maintainers:
    - hanouticelina
    - LysandreJik
    - osanseviero
    - Wauplin
    - BastianZim
    - sugatoray
    - setu4993
