schema_version: 1

context:
  version: 2.0.0

package:
  name: huggingface_hub
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/h/huggingface_hub/huggingface_hub-${{ version }}.tar.gz
  sha256: 375e5ad35cb3505efbf19c0cdd7e3fbf1e2304b12cd0e6b7fc8d75c6f5484619

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  python:
    entry_points:
      - hf=huggingface_hub.cli.hf:main
      - tiny-agents=huggingface_hub.inference._mcp.cli:app

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - setuptools
  run:
    - python >=${{ python_min }}
    - click >=8.4.2,<9.0.0
    - filelock >=3.10.0
    - fsspec >=2023.5.0
    - hf-xet >=1.6.0,<2.0.0; platform_machine == 'x86_64' or platform_machine == 'amd64' or platform_machine == 'AMD64' or platform_machine == 'arm64' or platform_machine == 'aarch64'
    - packaging >=20.9
    - pyyaml >=5.1
    - tomli >=1.1.0; python_version < '3.11'
    - tqdm >=4.42.1
    - typing_extensions >=4.1.0
    - httpx2 >=2.0.0,<3
tests:
  - python:
      python_version:
        - "*"
        - ${{ python_min }}.*
      pip_check: true
      imports:
        - huggingface_hub
  - script:
      - hf --help
      - tiny-agents --help

about:
  summary: Client library to download and publish models, datasets and other repos on the huggingface.co hub
  license: Apache-2.0
  license_file: LICENSE
  homepage: https://github.com/huggingface/huggingface_hub

extra:
  recipe-maintainers:
    - xhochy
    - hanouticelina
    - LysandreJik
    - osanseviero
    - Wauplin
    - BastianZim
    - sugatoray
    - setu4993
